### ISSUE TITLE
建议 cpan 上的 mojo-irc-server 里面的中文提示修改成英文

### ISSUE THREAD

**Issue by wxg4net** [sjdy521/Mojo-IRC-Server#1]
建议 cpan 上的 mojo-irc-server 里面的中文提示修改成英文 以方便非中文用户使用 http://cpansearch.perl.org/src/SJDY/Mojo-IRC-Server-1.7.1/lib/Mojo/IRC/Server.pm 我自己访问这个页面中文字符都乱码了

**Comment by hexsum** [comment]
一开始有考虑到locale多语言支持 不过后来觉得麻烦，你这个提议我记下了

发自网易邮箱大师
在2015年09月07日 08:04，wxg 写道:

建议 cpan 上的 mojo-irc-server 里面的中文提示修改成英文 以方便非中文用户使用 http://cpansearch.perl.org/src/SJDY/Mojo-IRC-Server-1.7.1/lib/Mojo/IRC/Server.pm 我自己访问这个页面中文字符都乱码了
