### ISSUE TITLE
Confusing network name

### ISSUE THREAD

**Issue by jberger** [sjdy521/Mojo-IRC-Server#2]
Hello. I'm interested in this project and I do hope eventually that there is enough documentation that I can try to start using it. In the meantime however, we (members of the Mojolicious core team) are concerned that the networks created using this module identify themselves as "The Mojo IRC Network ..." (see https://github.com/sjdy521/Mojo-IRC-Server/blob/30a0e4389754f94d631dbc22e64a329b22f9da15/lib/Mojo/IRC/Server/User.pm#L67 for example). I'd much rather that be something like "The IRC Network ... powered by Mojo::IRC::Server" or some other language so that it does not imply that the Mojo project is in control (or liable for) that particular network. 

Thanks

**Comment by kraih** [comment]
:+1:

**Comment by hexsum** [comment]
change “The Mojo IRC Network” to "Chinese IRC Network"
